name: Deploy Dev

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: Set checkout action token
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: SSH and Prepare
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 2280
          key: ${{ secrets.WORKFLOW_ACTION_TOKEN_2024 }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            git config --global user.name ${{ secrets.GIT_USER_NAME }}
            git config --global user.email ${{ secrets.GIT_USER_EMAIL }}

            cd ~/mhdc
            for filename in *.jar; do mv "$filename" "${filename}.old"; done;

            cd /home/app-client-v2/mhdc-main
            git checkout ${{ github.ref_name }}

      - name: Pull from branch
        run: git pull origin ${{ github.ref_name }}

      - uses: actions/setup-java@v5
        name: Set up JDK
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build jar file
        run: mvn -B package --file pom.xml

      - name: Copy result to mhdc jar folder
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 2280
          key: ${{ secrets.WORKFLOW_ACTION_TOKEN_2024 }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          source: "./target"
          target: "~/mhdc"

      - name: Remove temporary folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 2280
          key: ${{ secrets.WORKFLOW_ACTION_TOKEN_2024 }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd ~/mhdc
            mv ./target/*.jar ~/mhdc
            rm -rf target

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 2280
          key: ${{ secrets.WORKFLOW_ACTION_TOKEN_2024 }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd ~/mhdc
            ./build.sh
